using System.Diagnostics;
using System.Globalization;
using System.Reflection;
using System.Security.Claims;
using BTCPayServer.Abstractions.Constants;
using BTCPayServer.Abstractions.Extensions;
using BTCPayServer.Abstractions.Services;
using BTCPayServer.Data;
using BTCPayServer.Plugins.Flint.Data;
using BTCPayServer.Plugins.Flint.Models;
using BTCPayServer.Plugins.Flint.Sdk;
using BTCPayServer.Plugins.Flint.Services;
using BTCPayServer.Plugins.Flint.Tests.Fakes;
using BTCPayServer.Security;
using Ganss.Xss;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Abstractions;
using Microsoft.AspNetCore.Mvc.ApplicationParts;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Razor;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.Routing;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Razor.Hosting;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.FileProviders;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Localization;
using Xunit;

namespace BTCPayServer.Plugins.Flint.Tests.LocalRegtest;

/// <summary>
/// Writes the unilateral-exit page and the Advanced page's exit-state backup section out as standalone HTML
/// files, so the copy and the layout can be read in a browser without a logged-in BTCPay.
/// </summary>
/// <remarks>
/// <para>
/// <b>This is a developer tool, not a behavioural test.</b> Nothing here asserts what the pages say — the
/// assertions are "the page rendered and the file is not empty", because the artefact is the file. Everything
/// about the exit flow's behaviour is pinned in <see cref="SparkExitPageTests"/> and
/// <see cref="SparkUnilateralExitServiceTests"/>; what those cannot do is show a human what the page looks
/// like, which is the whole reason this file exists.
/// </para>
/// <para>
/// The pages are the real compiled Razor views, executed the way
/// <see cref="SetupTabViewRenderer"/> executes the setup partials: discovered as the
/// <see cref="RazorCompiledItemMetadataAttribute"/> the assemblies carry, instantiated, and run against a real
/// <see cref="ViewContext"/>. What surrounds them is MVC's own machinery rather than a transcription of
/// it — <c>AddMvcCore().AddViews()</c> supplies the production <c>IHtmlGenerator</c> (every <c>asp-for</c>,
/// <c>asp-validation-for</c>, label and form on these pages), the production model metadata, the view buffer
/// scope the tag-helper pipeline writes through, and the production view-component invoker, so the markup in
/// the files is generated by the same code that generates it in BTCPay.
/// </para>
/// <para>
/// <b>What is stood in, and why.</b> There is no HTTP request and no host process, so three things are
/// supplied that a real request would get for free, and each one is named here rather than left to be
/// discovered:
/// </para>
/// <list type="bullet">
/// <item>
/// <description>
/// <b>Routing.</b> <see cref="RoutedUrlHelper"/> composes the plugin's own route shape
/// (<c>/plugins/{storeId}/spark/…</c>) from the action names the views pass their tag helpers. It is not a
/// router and does not pretend to be one: it throws on any action this file has not been told about. Every
/// generated <c>href</c>/<c>action</c> is therefore the URL a real request would have produced, without a
/// route table.
/// </description>
/// </item>
/// <item>
/// <description>
/// <b>Authorisation.</b> <see cref="GrantAllAuthorizationService"/> grants
/// <c>CanModifyStoreSettings</c>, which is the role the pages are written for: the screenshots are meant to
/// show the operator's view, including the signed-hex table the <c>permission</c> attribute guards.
/// </description>
/// </item>
/// <item>
/// <description>
/// <b>Localisation.</b> <see cref="ScreenHostEnvironment"/> is the one fact the localiser plumbing reads off
/// the host. No resource files are found for it, so <c>StringLocalizer</c> returns the English keys the views
/// already carry — which is what a request to an untranslated BTCPay gets.
/// </description>
/// </item>
/// <item>
/// <description>
/// <b>View lookup.</b> <see cref="CompiledViewEngine"/> answers the names a view engine is asked for
/// (<c>_StatusMessage</c>, <c>Components/TitleHeader/Default</c>) out of the compiled views the two assemblies
/// carry, by the identifier the Razor compiler recorded. There is no file system in play, and a name it cannot
/// place fails with the identifiers it tried rather than rendering a blank space.
/// </description>
/// </item>
/// </list>
/// <para>
/// Nothing else is stubbed: <c>vc:title-header</c>, <c>vc:truncate-center</c> and the <c>vc:icon</c> inside
/// the latter go through MVC's own view-component invoker over the real component classes rendering their real
/// <c>Components/*/Default.cshtml</c>, the <c>_StatusMessage</c> partial is core's own compiled view (so a
/// refusal queued in <c>TempData</c> — the "nothing worth exiting" state — renders as the same alert the
/// operator would see), and the tag helpers are MVC's.
/// </para>
/// <para>
/// <b>One class, in the serialised collection.</b> The exit feature is behind a process-wide environment
/// switch and the Advanced page's backup section only renders behind it, so the class joins
/// <see cref="UnilateralExitTestCollection"/> and every test restores the variable in a <c>finally</c>.
/// </para>
/// <para>
/// Run it with <c>dotnet test --filter "FullyQualifiedName~RenderExitScreensTests"</c>; the files land in
/// <see cref="ExitScreenRenderer.OutputDirectory"/> and are inert (they link BTCPay's own stylesheets by
/// absolute URL, so they want the server this repo's checkout already runs).
/// </para>
/// </remarks>
[Collection(UnilateralExitTestCollection.Name)]
public class RenderExitScreensTests
{
    private const string Store = SparkSurfaceHarness.AttackerStore;
    private const string Gate = "FLINT_EXPERIMENTAL_UNILATERAL_EXIT";

    /// <summary>A regtest address, so a destination in a screen reads like one a merchant would type.</summary>
    private const string Destination = "bcrt1qt8hufshrz62z5vj4q40uqx6c6ytlujy5s03gwm";

    /// <summary>
    /// The pre-quote disclosure: acknowledged by nobody, nothing in flight, a balance to quote against.
    /// </summary>
    /// <remarks>
    /// The order is the feature: the disclosure and its acknowledgement come before any balance, fee field or
    /// address input, so this is the screen that has to be read for whether that is still true.
    /// </remarks>
    [Fact]
    public async Task The_disclosure_screen_renders()
    {
        using var gate = FeatureGate();

        var html = await RenderExitScreenAsync(
            Page(disclosureAcknowledged: false, balanceSats: 250_000));

        WriteScreen("01-disclosure.html", html);
    }

    /// <summary>
    /// The quote form, opening at the rate the service recommended.
    /// </summary>
    [Fact]
    public async Task The_quote_form_renders_at_the_recommended_rate()
    {
        using var gate = FeatureGate();

        var html = await RenderExitScreenAsync(
            Page(balanceSats: 900_000, recommendedFeeRateSatPerVbyte: 3));

        WriteScreen("02-quote-form.html", html);
    }

    /// <summary>
    /// The same form with no recommendation to open at — a regtest server with no explorer override, or an
    /// explorer that could not be read. The field falls back to the plugin's own floor rather than being blank.
    /// </summary>
    [Fact]
    public async Task The_quote_form_renders_without_a_recommendation()
    {
        using var gate = FeatureGate();

        var html = await RenderExitScreenAsync(
            Page(balanceSats: 900_000, recommendedFeeRateSatPerVbyte: null));

        WriteScreen("03-quote-form-no-recommendation.html", html);
    }

    /// <summary>
    /// A quote that came back with nothing worth exiting. The refusal is the service's own sentence, carried
    /// into the page exactly as the controller carries it — through <c>TempData</c>, which is what the
    /// <c>_StatusMessage</c> partial reads.
    /// </summary>
    [Fact]
    public async Task The_nothing_worth_exiting_screen_renders()
    {
        using var gate = FeatureGate();

        var html = await RenderExitScreenAsync(
            Page(balanceSats: 900_000, recommendedFeeRateSatPerVbyte: 3),
            errorMessage: SparkUnilateralExitService.NothingWorthExiting);

        WriteScreen("04-nothing-worth-exiting.html", html);
    }

    /// <summary>
    /// A quoted exit waiting for its funding: the funding address, the amount and the rate the record was
    /// quoted at.
    /// </summary>
    /// <remarks>
    /// The live recommendation is deliberately a different number from the record's (7 against the record's
    /// 12). The field has to show the record's, because that is the rate the leaves in front of the operator
    /// were priced at, and a screen where the two agree proves nothing about which one won.
    /// </remarks>
    [Fact]
    public async Task The_awaiting_funding_screen_renders()
    {
        using var gate = FeatureGate();

        var record = AwaitingFunding();
        var html = await RenderExitScreenAsync(
            Page(
                balanceSats: 900_000,
                recommendedFeeRateSatPerVbyte: 7,
                activeRecord: record,
                // The explorer answered and nothing has arrived yet: zero, not null. Null is "nobody knows",
                // and the page says so differently.
                fundingReceivedSat: 0,
                fundingLargestOutputSat: 0,
                leafCount: 2,
                fundingKeyPath: "m/84'/1'/4607060'/0/3"));

        WriteScreen("05-awaiting-funding.html", html);
    }

    /// <summary>The Advanced page with an exit-state backup stored.</summary>
    [Fact]
    public async Task The_advanced_backup_screen_renders_when_one_is_stored()
    {
        using var gate = FeatureGate();

        var html = await RenderAdvancedScreenAsync(storedBackup: true);

        WriteScreen("06-advanced-backup.html", html);
    }

    /// <summary>The same section with nothing stored — the state most stores are in.</summary>
    [Fact]
    public async Task The_advanced_backup_screen_renders_when_none_is_stored()
    {
        using var gate = FeatureGate();

        var html = await RenderAdvancedScreenAsync(storedBackup: false);

        WriteScreen("07-advanced-backup-none.html", html);
    }

    #region Fixtures

    /// <summary>
    /// One service read, with every field named, exactly as <see cref="SparkExitPageTests"/> builds it.
    /// </summary>
    /// <remarks>
    /// Named optional parameters rather than a positional constructor call, so a field added to the record does
    /// not silently shift what an existing screen was showing.
    /// </remarks>
    private static UnilateralExitPageData Page(
        bool walletRunning = true,
        bool disclosureAcknowledged = true,
        long balanceSats = 0,
        long? recommendedFeeRateSatPerVbyte = null,
        UnilateralExitRecord? activeRecord = null,
        IReadOnlyList<UnilateralExitRecord>? history = null,
        long? fundingReceivedSat = null,
        long? fundingLargestOutputSat = null,
        int? leafCount = null,
        string? fundingKeyPath = null,
        IReadOnlyList<SparkExitTransaction>? transactions = null,
        bool transactionsUnreadable = false,
        IReadOnlyList<SparkExitTransaction>? pendingBroadcast = null) =>
        new(
            walletRunning,
            disclosureAcknowledged,
            balanceSats,
            recommendedFeeRateSatPerVbyte,
            activeRecord,
            history ?? [],
            fundingReceivedSat,
            fundingLargestOutputSat,
            leafCount,
            fundingKeyPath,
            transactions,
            transactionsUnreadable,
            pendingBroadcast);

    /// <summary>
    /// A quoted exit waiting for its funding, at 12 sat/vB — a rate no explorer would have recommended, which
    /// is the point of it.
    /// </summary>
    private static UnilateralExitRecord AwaitingFunding() => new()
    {
        Id = "record-7",
        StoreId = Store,
        Status = UnilateralExitStatus.AwaitingFunding,
        // A plausible quote time rather than the epoch the unit-test fixture uses: these screens are read by a
        // human, and a 1970 date reads as a broken page instead of as the state being shown.
        CreatedUtc = new DateTimeOffset(2026, 9, 14, 9, 12, 0, TimeSpan.Zero),
        UpdatedUtc = new DateTimeOffset(2026, 9, 14, 9, 12, 0, TimeSpan.Zero),
        DestinationAddress = Destination,
        FeeRateSatPerVbyte = 12,
        RecoverableValueSat = 400_000,
        TotalFeeSat = 9_000,
        SingleUtxoFundingSat = 4_300,
        FundingAddress = "bcrt1q0lxqmm5qkcvpq7jqmkmvsp0hv7jwqfq38nhdqf"
    };

    /// <summary>
    /// The exit page's model, projected by the controller — the same call a browser's GET makes.
    /// </summary>
    /// <remarks>
    /// Deliberately not hand-built: <see cref="SparkController"/> owns the projection (including which rate the
    /// field opens at, and that a record's destination and rate win over anything the form was posted with),
    /// so the screens are of what the page actually receives rather than of what this file believes it would.
    /// </remarks>
    private static async Task<string> RenderExitScreenAsync(
        UnilateralExitPageData page, string? errorMessage = null)
    {
        var h = SparkSurfaceHarness.Create(
            configureAttackerStore: true, unilateralExit: new ScreenExitService(page));

        if (errorMessage is not null)
        {
            // The controller's own channel on a refusal, and the only place the page gets its copy from.
            h.Mvc.TempData[WellKnownTempData.ErrorMessage] = errorMessage;
        }

        var view = Assert.IsType<ViewResult>(await h.Mvc.Exit(Store, CancellationToken.None));
        var model = Assert.IsType<SparkExitViewModel>(view.Model);

        return await ExitScreenRenderer.RenderAsync(
            ExitScreenRenderer.ExitItemPath, model, h.Mvc.TempData);
    }

    /// <summary>
    /// The Advanced page's model, projected by the controller, with the stored backup set the way a saved
    /// backup would leave it.
    /// </summary>
    private static async Task<string> RenderAdvancedScreenAsync(bool storedBackup)
    {
        var h = SparkSurfaceHarness.Create(configureAttackerStore: true);

        // Presence is all the page is told, and all it can be: the controller hands the view a timestamp and
        // never the blob, so this scripts the file store a real backup would have left behind.
        if (storedBackup)
        {
            await h.ExitStateBackups.WriteAsync(Store, """{"version":1,"leaves":[]}""", CancellationToken.None);
            h.ExitStateBackups.TakenAt = new DateTimeOffset(2026, 9, 16, 12, 0, 0, TimeSpan.Zero);
        }

        var view = Assert.IsType<ViewResult>(await h.Mvc.Advanced(Store, CancellationToken.None));
        var model = Assert.IsType<SparkAdvancedViewModel>(view.Model);

        return await ExitScreenRenderer.RenderAsync(
            ExitScreenRenderer.AdvancedItemPath, model, h.Mvc.TempData);
    }

    /// <summary>Writes one screen to the output directory, which is the deliverable.</summary>
    private static void WriteScreen(string fileName, string html)
    {
        Directory.CreateDirectory(ExitScreenRenderer.OutputDirectory);
        File.WriteAllText(Path.Combine(ExitScreenRenderer.OutputDirectory, fileName), html);

        Assert.False(string.IsNullOrWhiteSpace(html));
    }

    /// <summary>
    /// Sets the feature switch for one test and puts back whatever was there.
    /// </summary>
    /// <remarks>
    /// The switch is process-wide and <c>Constants.UnilateralExitEnabled</c> is a property precisely so this
    /// works. Both pages here need it on: the controller refuses to build the exit model without it, and the
    /// Advanced page renders no backup section at all.
    /// </remarks>
    private static IDisposable FeatureGate() => new EnvironmentSwitch(Gate, "1");

    private sealed class EnvironmentSwitch : IDisposable
    {
        private readonly string _name;
        private readonly string? _previous;

        public EnvironmentSwitch(string name, string? value)
        {
            _name = name;
            _previous = Environment.GetEnvironmentVariable(name);
            Environment.SetEnvironmentVariable(name, value);
        }

        public void Dispose() => Environment.SetEnvironmentVariable(_name, _previous);
    }

    /// <summary>
    /// The exit service the page reads: whatever this file says, and nothing else — the write methods are not
    /// reachable from a GET and say so rather than returning a plausible success.
    /// </summary>
    private sealed class ScreenExitService(UnilateralExitPageData page) : ISparkUnilateralExitService
    {
        public Task<UnilateralExitPageData> ReadAsync(
            string storeId, CancellationToken cancellationToken = default) =>
            Task.FromResult(page);

        public Task<UnilateralExitOpResult> AcknowledgeDisclosureAsync(
            string storeId, CancellationToken cancellationToken = default) => NotAWrite();

        public Task<UnilateralExitOpResult> QuoteAsync(
            string storeId, long feeRateSatPerVbyte, string destinationAddress,
            CancellationToken cancellationToken = default) => NotAWrite();

        public Task<UnilateralExitOpResult> BuildAsync(
            string storeId, string recordId, CancellationToken cancellationToken = default) => NotAWrite();

        public Task<UnilateralExitOpResult> AbandonAsync(
            string storeId, string recordId, CancellationToken cancellationToken = default) => NotAWrite();

        public Task<UnilateralExitOpResult> MarkCompletedAsync(
            string storeId, string recordId, CancellationToken cancellationToken = default) => NotAWrite();

        public Task<UnilateralExitOpResult> CheckAsync(
            string storeId, string recordId, CancellationToken cancellationToken = default) => NotAWrite();

        public Task<UnilateralExitOpResult> SetExitStateBackupAsync(
            string storeId, string? exitState, CancellationToken cancellationToken = default) => NotAWrite();

        public Task<UnilateralExitOpResult> SetExplorerUrlAsync(
            string storeId, string? esploraApiUrl, CancellationToken cancellationToken = default) => NotAWrite();

        private static Task<UnilateralExitOpResult> NotAWrite() => throw new NotSupportedException(
            "These screens are rendered from a GET. Only ReadAsync is reachable, and a screen that reaches "
            + "for a write is not a screen this tool can render.");
    }

    #endregion
}

/// <summary>
/// Executes the plugin's compiled pages outside a request and wraps the result in the same document skeleton
/// BTCPay's own layout produces, so the files can be opened (or screenshotted) as they are.
/// </summary>
/// <remarks>
/// <para>
/// The skeleton is deliberately not a copy of <c>_Layout.cshtml</c> — that layout needs a signed-in user, a
/// navigation tree and a store, none of which exist without a request. What it reproduces is the three things
/// the styling hangs off: the four stylesheets <c>LayoutHead</c> links (<c>bootstrap</c>, <c>layout</c>,
/// <c>site</c> and the OpenSans face), the body class the layout puts on <c>&lt;body&gt;</c>, and the
/// <c>&lt;main id="mainContent"&gt;&lt;section&gt;</c> wrapper <c>layout.css</c> takes its content padding and
/// max-width from. With those, the typography, tables, alerts, forms and the <c>col-xl-8</c> column all lay out
/// as they do in BTCPay.
/// </para>
/// <para>
/// The links are absolute URLs to a running BTCPay rather than <c>~/main/…</c> paths, because a file on disk has
/// no app root to resolve those against. The theme file is the light one the layout links through
/// <c>LayoutHeadTheme</c> — it is where BTCPay's colours and type scale live, so without it the alerts and
/// headings render as a browser default. Its dark sibling is left out on purpose: the layout's script is what
/// swaps it in, and no script runs here. Nothing else is loaded: no JS, no vendor CSS, no navigation.
/// </para>
/// </remarks>
internal static class ExitScreenRenderer
{
    /// <summary>Where the screens are written. Cleared of nothing — one file per screen, overwritten in place.</summary>
    public const string OutputDirectory = "/tmp/flint-screens";

    /// <summary>The compiled item path of the unilateral-exit page.</summary>
    public const string ExitItemPath = "/Views/Spark/Exit.cshtml";

    /// <summary>The compiled item path of the Advanced page.</summary>
    public const string AdvancedItemPath = "/Views/Spark/Advanced.cshtml";

    /// <summary>
    /// The running BTCPay the splash assets and the plugin's own route prefix are named against, matching the
    /// host the local regtest stack serves on.
    /// </summary>
    private const string PublicBaseUrl = "http://127.0.0.1:14142";

    /// <summary>
    /// The core assembly: where BTCPay's shared views (the status-message partial) and its view components
    /// (the title header, the truncated value, the icon) are compiled. Referenced through a type that is part
    /// of the compile, because an assembly name is a string that can go stale silently.
    /// </summary>
    private static readonly Assembly HostAssembly = typeof(BTCPayServer.ViewDataDictionaryExtensions).Assembly;

    /// <summary>The stylesheets <c>_Layout</c> links through <c>LayoutHead</c>, in its order.</summary>
    private const string Stylesheets =
        """
        <link href="http://127.0.0.1:14142/main/bootstrap/bootstrap.css" rel="stylesheet" />
        <link href="http://127.0.0.1:14142/main/layout.css" rel="stylesheet" />
        <link href="http://127.0.0.1:14142/main/site.css" rel="stylesheet" />
        <link href="http://127.0.0.1:14142/main/fonts/OpenSans.css" rel="stylesheet" />
        <link href="http://127.0.0.1:14142/main/themes/default.css" rel="stylesheet" />
        """;

    /// <summary>
    /// Renders one compiled page over the given model and returns a document that can be opened in a browser.
    /// </summary>
    /// <param name="compiledItemPath">The <c>.cshtml</c> path the Razor compiler recorded, e.g.
    /// <see cref="ExitItemPath"/>.</param>
    /// <param name="model">The page's view model, as the controller built it.</param>
    /// <param name="tempData">
    /// The request's <c>TempData</c>, so a status message the page would have shown after a redirect is on the
    /// screen rather than missing.
    /// </param>
    public static async Task<string> RenderAsync(
        string compiledItemPath, object model, ITempDataDictionary tempData)
    {
        var pageType = CompiledPages.PageType(compiledItemPath)
            ?? throw new InvalidOperationException(
                $"No compiled page carries the identifier '{compiledItemPath}'. Either the view was renamed or "
                + "the assembly it is compiled into is not one this renderer searches.");

        var httpContext = new DefaultHttpContext();
        httpContext.RequestServices = BuildRequestServices(httpContext);
        // The same channel core's authorization filter writes on a store-authorized request, and where the
        // routed URL helper reads the store id from.
        httpContext.SetStoreData(new StoreData { Id = StoreIdFor(model) });

        var viewData = ViewDataFor(pageType, model);
        var writer = new StringWriter(CultureInfo.InvariantCulture);
        var viewContext = new ViewContext(
            new ActionContext(httpContext, new RouteData(), new ActionDescriptor()),
            new CompiledView(pageType, compiledItemPath),
            viewData,
            tempData,
            writer,
            new HtmlHelperOptions())
        {
            ExecutingFilePath = compiledItemPath
        };

        await viewContext.View.RenderAsync(viewContext);

        return Document(viewData.GetTitle() ?? compiledItemPath, writer.ToString());
    }

    /// <summary>Wraps a rendered body in the document skeleton described on the class.</summary>
    private static string Document(string title, string body) =>
        $"""
         <!doctype html>
         <html lang="en">
         <head>
             <meta charset="utf-8" />
             <meta name="viewport" content="width=device-width, initial-scale=1.0" />
             <title>{title}</title>
         {Stylesheets}
         </head>
         <body class="d-flex flex-column flex-lg-row min-vh-100">
             <main id="mainContent">
                 <section>
         {body}
                 </section>
             </main>
         </body>
         </html>
         """;

    /// <summary>
    /// The store id both pages are rendered for, read off the view model rather than passed in, because the
    /// pages themselves read it the same way.
    /// </summary>
    private static string StoreIdFor(object model) => model switch
    {
        SparkExitViewModel exit => exit.StoreId,
        SparkAdvancedViewModel advanced => advanced.StoreId,
        _ => throw new NotSupportedException(
            $"This renderer knows the store id on {nameof(SparkExitViewModel)} and {nameof(SparkAdvancedViewModel)} "
            + $"only, and was handed a {model.GetType().Name}.")
    };

    /// <summary>
    /// The page's view data, in the exact generic type the page declares — the compiled page casts
    /// <c>ViewData</c> to <c>ViewDataDictionary&lt;TModel&gt;</c> on every read, so an untyped dictionary is an
    /// exception rather than a render.
    /// </summary>
    private static ViewDataDictionary ViewDataFor(Type pageType, object model)
    {
        var modelType = pageType.BaseType is { IsGenericType: true } baseType
            ? baseType.GetGenericArguments()[0]
            : throw new InvalidOperationException(
                $"The compiled page {pageType.Name} does not derive from a generic RazorPage, which is not a "
                + "shape this renderer knows how to feed.");

        var viewData = (ViewDataDictionary)Activator.CreateInstance(
            typeof(ViewDataDictionary<>).MakeGenericType(modelType),
            new EmptyModelMetadataProvider(),
            new ModelStateDictionary())!;
        viewData.Model = model;
        return viewData;
    }

    /// <summary>
    /// The request's service provider: MVC's own view-features services, plus the handful of things a request
    /// would have had from the host rather than from MVC.
    /// </summary>
    /// <remarks>
    /// Every override is registered <em>after</em> MVC's own registration so it is the one resolved; the
    /// order is load-bearing and MVC registers all of these with <c>TryAdd</c>.
    /// </remarks>
    private static ServiceProvider BuildRequestServices(HttpContext httpContext)
    {
        var services = new ServiceCollection();

        // The production generator (every asp-for, label, validation message and form on these pages), the
        // production model metadata and expression provider, a memory-pooled view buffer scope for the
        // tag-helper pipeline, the default view-component machinery, and the TempData dictionary factory.
        var mvc = services.AddMvcCore().AddViews().AddViewLocalization();
        // The view components the pages call (the title header, the truncated value, the icon inside it) are
        // discovered by MVC from the application's parts, so both assemblies that carry these pages are
        // declared as parts — the same registration BTCPay's own plugin loader makes for a plugin assembly.
        mvc.PartManager.ApplicationParts.Add(new AssemblyPart(typeof(SparkPlugin).Assembly));
        mvc.PartManager.ApplicationParts.Add(new AssemblyPart(HostAssembly));
        services.AddLocalization();
        // Core's `_ViewImports` injects the concrete ViewLocalizer, and BTCPay registers it itself
        // (TranslationsPlugin); the same registration here, over the framework's HTML localizer factory.
        services.TryAddSingleton<ViewLocalizer>();

        // The non-generic localizer core's views inject, rooted at the assembly those views live in. No
        // resource files exist for it, so every lookup answers with the key the view already carries — which is
        // what a request to an untranslated BTCPay gets.
        services.TryAddSingleton<IStringLocalizer>(sp => sp.GetRequiredService<IStringLocalizerFactory>()
            .Create(typeof(BTCPayServer.ViewDataDictionaryExtensions)));

        // The tag-helper factory and its activator are internal to MVC and are instantiated here the way MVC's
        // DI does it, for the reason SetupTabViewRenderer gives: these views get exactly the tag helpers a real
        // request would build for them, including the generated ones behind `vc:`.
        services.AddSingleton<ITagHelperFactory>(CreateDefaultTagHelperFactory());

        // One listener, serving both the DiagnosticListener a view component asks for and the DiagnosticSource
        // the page's own [RazorInject] property asks for.
        var diagnostics = new DiagnosticListener("BTCPayServer.Plugins.Flint.Screens");
        services.AddSingleton(diagnostics);
        services.AddSingleton<DiagnosticSource>(diagnostics);

        // What BTCPay's own container supplies on a real request: the sanitizing HTML helper, the permission
        // service behind the `permission` attribute, the context accessor, and the host.
        services.AddSingleton(sp => new Safe(
            sp.GetRequiredService<IHtmlHelper>(),
            sp.GetRequiredService<IJsonHelper>(),
            new HtmlSanitizer()));
        services.AddSingleton<IAuthorizationService, GrantAllAuthorizationService>();
        services.AddSingleton<IHttpContextAccessor>(new FixedHttpContextAccessor(httpContext));
        services.AddSingleton<IWebHostEnvironment, ScreenHostEnvironment>();

        // The two stand-ins the class remarks name: route composition, and view lookup over the compiled views
        // of the two assemblies above rather than over a file system.
        services.AddSingleton<IUrlHelperFactory, RoutedUrlHelperFactory>();
        services.AddSingleton<ICompositeViewEngine, CompiledViewEngine>();

        return services.BuildServiceProvider();
    }

    /// <summary>
    /// The production <see cref="ITagHelperFactory"/> over the production activator, both internal and
    /// therefore reflection-instantiated rather than reimplemented.
    /// </summary>
    private static ITagHelperFactory CreateDefaultTagHelperFactory()
    {
        var assembly = typeof(ITagHelperFactory).Assembly;
        var activatorType = assembly.GetType(
            "Microsoft.AspNetCore.Mvc.Razor.Infrastructure.DefaultTagHelperActivator", throwOnError: true)!;
        var factoryType = assembly.GetType(
            "Microsoft.AspNetCore.Mvc.Razor.DefaultTagHelperFactory", throwOnError: true)!;
        return (ITagHelperFactory)Activator.CreateInstance(
            factoryType, Activator.CreateInstance(activatorType))!;
    }

    /// <summary>
    /// Executes one compiled page the way the Razor view engine does: a fresh instance per render, its
    /// <c>[RazorInject]</c> properties filled from the request's services, then the page's own body.
    /// </summary>
    internal static async Task ExecuteAsync(Type pageType, string itemPath, ViewContext viewContext)
    {
        var page = (IRazorPage)Activator.CreateInstance(pageType)!;
        page.Path = itemPath;
        page.ViewContext = viewContext;
        ActivateInjects(page, viewContext, itemPath);

        await page.ExecuteAsync();
    }

    /// <summary>
    /// Fills a page's <c>[RazorInject]</c> properties.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This is <c>RazorPagePropertyActivator</c>'s contract, not an invention: a service is required for every
    /// injected property, <c>IViewContextAware</c> services are contextualized with the view context they were
    /// injected into, <c>ViewData</c> comes from the context rather than from DI, and a <c>ViewDataDictionary</c>
    /// of any other shape than the page's own is an error rather than a silent null.
    /// </para>
    /// <para>
    /// The attribute is matched by name because <c>RazorInjectAttribute</c> is internal to MVC, and every
    /// property it decorates is here on purpose: a view that grows an injection this renderer cannot satisfy
    /// fails with the property's name in the message rather than rendering something missing.
    /// </para>
    /// </remarks>
    private static void ActivateInjects(IRazorPage page, ViewContext viewContext, string itemPath)
    {
        foreach (var property in page.GetType().GetProperties(
                     BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance))
        {
            if (!IsRazorInject(property))
                continue;

            if (!property.CanWrite)
            {
                throw new InvalidOperationException(
                    $"{page.GetType().Name}.{property.Name} is an injected property with no setter, so the page "
                    + $"at '{itemPath}' cannot be activated.");
            }

            object? value;
            if (typeof(ViewDataDictionary).IsAssignableFrom(property.PropertyType))
            {
                value = viewContext.ViewData;
            }
            else if (property.PropertyType == typeof(IUrlHelper))
            {
                value = viewContext.HttpContext.RequestServices
                    .GetRequiredService<IUrlHelperFactory>().GetUrlHelper(viewContext);
            }
            else
            {
                value = viewContext.HttpContext.RequestServices.GetService(property.PropertyType)
                    ?? throw new InvalidOperationException(
                        $"The page at '{itemPath}' injects {property.PropertyType.FullName} into "
                        + $"{property.Name}, and nothing in this renderer's services supplies it. Add it to "
                        + "BuildRequestServices rather than to the view.");
            }

            (value as IViewContextAware)?.Contextualize(viewContext);
            property.SetValue(page, value);
        }
    }

    private static bool IsRazorInject(PropertyInfo property) =>
        property.GetCustomAttributes(inherit: true)
            .Any(attribute => attribute.GetType().FullName == "Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute");

    /// <summary>
    /// One compiled <c>.cshtml</c> in one assembly, executed when the view engine asks for it.
    /// </summary>
    private sealed class CompiledView(Type pageType, string itemPath) : IView
    {
        public string Path { get; } = itemPath;

        public Task RenderAsync(ViewContext viewContext) => ExecuteAsync(pageType, Path, viewContext);
    }

    /// <summary>
    /// Finds a compiled page by the name a view engine would have been given for it.
    /// </summary>
    /// <remarks>
    /// The names are the same ones the Razor view engine searches for: a component view arrives as
    /// <c>Components/{Component}/Default</c>, a partial as <c>_StatusMessage</c>, and both are then looked for
    /// at the identifier the compiler recorded. There is no file system in play, so the searched locations are
    /// the identifiers actually tried.
    /// </remarks>
    private sealed class CompiledViewEngine : ICompositeViewEngine
    {
        /// <summary>No nested engines: this one serves the handful of compiled views the plugin's pages call.</summary>
        public IReadOnlyList<IViewEngine> ViewEngines => [];

        public ViewEngineResult GetView(string? executingFilePath, string viewPath, bool isMainPage) =>
            Find(viewPath);

        public ViewEngineResult FindView(ActionContext context, string viewName, bool isMainPage) =>
            Find(viewName);

        public ViewEngineResult FindPartialView(ActionContext context, string partialName, bool isMainPage) =>
            Find(partialName);

        private static ViewEngineResult Find(string viewName)
        {
            var name = viewName.TrimStart('/');
            if (name.EndsWith(".cshtml", StringComparison.OrdinalIgnoreCase))
                name = name[..^".cshtml".Length];

            var searched = new List<string>
            {
                $"/{name}.cshtml",
                $"/Views/{name}.cshtml",
                $"/Views/Shared/{name}.cshtml",
                $"/Views/Spark/{name}.cshtml"
            };

            foreach (var identifier in searched)
            {
                if (CompiledPages.PageType(identifier) is { } pageType)
                    return ViewEngineResult.Found(viewName, new CompiledView(pageType, identifier));
            }

            return ViewEngineResult.NotFound(viewName, searched);
        }
    }

    /// <summary>
    /// The plugin's own route shape, composed from the action names the views pass their tag helpers.
    /// </summary>
    /// <remarks>
    /// <see cref="SparkController"/> routes under <c>plugins/{storeId}/spark</c> with the suffixes below, which
    /// is what a real request resolves an <c>asp-action</c> to. Composing them here keeps every generated
    /// <c>href</c> and form <c>action</c> looking like the real page's without standing up a route table — and
    /// an action this table has never heard of throws rather than rendering a link to nowhere.
    /// </remarks>
    private sealed class RoutedUrlHelperFactory : IUrlHelperFactory
    {
        public IUrlHelper GetUrlHelper(ActionContext context) => new RoutedUrlHelper(context);
    }

    private sealed class RoutedUrlHelper(ActionContext actionContext) : IUrlHelper
    {
        private static readonly Dictionary<string, string> SparkActionSuffixes = new(StringComparer.Ordinal)
        {
            ["Status"] = "status",
            ["Setup"] = "setup",
            ["Sweep"] = "sweep",
            ["Advanced"] = "advanced",
            ["Deposit"] = "deposit",
            ["Exit"] = "exit",
            ["Remove"] = "remove",
            ["StableBalance"] = "stable-balance",
            ["AcknowledgeExit"] = "exit/acknowledge",
            ["QuoteExit"] = "exit/quote",
            ["BuildExit"] = "exit/build",
            ["CheckExit"] = "exit/check",
            ["AbandonExit"] = "exit/abandon",
            ["CompleteExit"] = "exit/complete",
            ["SetExitExplorer"] = "exit/explorer",
            ["AdvancedSweep"] = "advanced/sweep",
            ["AdvancedApiKey"] = "advanced/api-key",
            ["ExportExitState"] = "advanced/exit-state/export",
            ["DownloadExitStateBackup"] = "advanced/exit-state/download",
            ["SetExitStateBackup"] = "advanced/exit-state"
        };

        public ActionContext ActionContext { get; } = actionContext;

        /// <summary>
        /// The one link shape these pages generate, through the extension the tag helpers and
        /// <c>DefaultHtmlGenerator</c> both call.
        /// </summary>
        public string? Action(UrlActionContext actionContext) =>
            Compose(actionContext.Action, actionContext.Values, actionContext.Fragment);

        /// <summary>
        /// A route-values link: the same composition, because a named route is not something these pages use.
        /// </summary>
        public string? RouteUrl(UrlRouteContext routeContext)
        {
            if (routeContext.RouteName is not null)
            {
                throw new NotSupportedException(
                    $"The rendered screens must not link by route name ('{routeContext.RouteName}'); they use "
                    + "asp-action, which arrives here as route values.");
            }

            return Compose(null, routeContext.Values, routeContext.Fragment);
        }

        /// <summary>
        /// A content path: <c>~/</c> is the app root, which a file on disk does not have, so it resolves to the
        /// running BTCPay the splash assets are served from. Anything else is already a path.
        /// </summary>
        public string Content(string? contentPath) => contentPath switch
        {
            null => string.Empty,
            { Length: 0 } => string.Empty,
            _ when contentPath.StartsWith("~/", StringComparison.Ordinal) => PublicBaseUrl + contentPath[1..],
            _ => contentPath
        };

        public string? Link(string? routeName, object? values) => Unused<string>(nameof(Link));

        public bool IsLocalUrl(string? url) => Unused<bool>(nameof(IsLocalUrl));

        /// <summary>
        /// <c>/plugins/{storeId}/spark/{suffix}</c>, with the store id the view passed — or, failing that, the
        /// one the request was authorized for, which is how a real request's route values are filled.
        /// </summary>
        private string Compose(string? action, object? values, string? fragment)
        {
            if (action is null)
            {
                throw new NotSupportedException(
                    $"A link with no action was rendered ({new RouteValueDictionary(values).Count} route values); "
                    + "these pages only generate asp-action links, and a guessed URL would be a broken one.");
            }

            if (!SparkActionSuffixes.TryGetValue(action, out var suffix))
            {
                throw new NotSupportedException(
                    $"The rendered screens must not link to SparkController.{action}; add its route suffix to "
                    + "SparkActionSuffixes deliberately if a page starts offering it.");
            }

            var routeValues = new RouteValueDictionary(values);
            var storeId = routeValues["storeId"] as string
                          ?? ActionContext.HttpContext.GetStoreDataOrNull()?.Id
                          ?? throw new InvalidOperationException(
                              $"A link to SparkController.{action} was rendered without a store id on either "
                              + "the route values or the request.");

            return $"{PublicBaseUrl}/plugins/{storeId}/spark/{suffix}{fragment}";
        }

        private static T Unused<T>(string member) => throw new NotSupportedException(
            $"The rendered exit screens must not call IUrlHelper.{member}; extend RoutedUrlHelper deliberately "
            + "if a page starts needing it.");
    }

    /// <summary>
    /// The compiled pages of the two assemblies that carry them, found once and remembered.
    /// </summary>
    /// <remarks>
    /// Discovery is MVC's own: <see cref="RazorCompiledItemLoader"/> reads the
    /// <see cref="RazorCompiledItemMetadataAttribute"/> markers the Razor compiler writes, which is the same
    /// mechanism the view engine uses to find a view at runtime. The plugin's pages and core's shared views are
    /// both in reach from here, and the returned type is the real compiled page, never a transcription of it.
    /// </remarks>
    private static class CompiledPages
    {
        private static readonly Lazy<Dictionary<string, Type>> ByIdentifier = new(() =>
        {
            var loader = new RazorCompiledItemLoader();
            var pages = new Dictionary<string, Type>(StringComparer.Ordinal);
            foreach (var assembly in new[] { typeof(SparkPlugin).Assembly, HostAssembly })
            {
                foreach (var item in loader.LoadItems(assembly))
                {
                    if (item.Kind == "mvc.1.0.view" || item.Kind == "mvc.1.0.razor-page")
                        pages[item.Identifier] = item.Type;
                }
            }

            return pages;
        });

        public static Type? PageType(string identifier) =>
            ByIdentifier.Value.TryGetValue(identifier, out var pageType) ? pageType : null;
    }

    /// <summary>Grants every permission check, so a screen shows the page, not who is looking at it.</summary>
    private sealed class GrantAllAuthorizationService : IAuthorizationService
    {
        public Task<AuthorizationResult> AuthorizeAsync(
            ClaimsPrincipal user, object? resource, IEnumerable<IAuthorizationRequirement> requirements) =>
            Task.FromResult(AuthorizationResult.Success());

        public Task<AuthorizationResult> AuthorizeAsync(
            ClaimsPrincipal user, object? resource, string policyName) =>
            Task.FromResult(AuthorizationResult.Success());
    }

    /// <summary>Hands the permission helper the very context the render is running over.</summary>
    private sealed class FixedHttpContextAccessor(HttpContext httpContext) : IHttpContextAccessor
    {
        public HttpContext? HttpContext { get; set; } = httpContext;
    }

    /// <summary>
    /// The one fact the localiser plumbing reads off a host. There is no host process here, so it is named
    /// rather than discovered; no resource files exist for it, which leaves the views' own English keys in
    /// place.
    /// </summary>
    private sealed class ScreenHostEnvironment : IWebHostEnvironment
    {
        public string ApplicationName { get; set; } = "BTCPayServer";

        public IFileProvider WebRootFileProvider { get; set; } = new NullFileProvider();

        public string WebRootPath { get; set; } = string.Empty;

        public string EnvironmentName { get; set; } = Environments.Development;

        public string ContentRootPath { get; set; } = string.Empty;

        public IFileProvider ContentRootFileProvider { get; set; } = new NullFileProvider();
    }
}